### ISSUE TITLE
Doesn't send when deployed as part of OpenCensus Service

### ISSUE THREAD

**Issue by garthk** [honeycombio/opencensus-exporter#14]
@akvanhar, the folks at census-instrumentation/opencensus-service#550 referred me here, so I'm raising a tracking issue. I regret I don't have the Go skills to fire up a debugger and figure out what's going on.

> From my reading of `README.md`, I believe `occollector_linux`  should take this `config.yaml`, accept spans on 55678, and send them to Honeycomb:
…
> … but I can't find any evidence spans are being sent

**Comment by akvanhar** [comment]
Hi @garthk , I did some investigation and as far as I can tell, adding go modules should help solve this, which has been added as of https://github.com/honeycombio/opencensus-exporter/releases/tag/v1.0.1

This worked for me when running the agent locally. I've added an explicit Honeycomb example to the OpenCensus website.

https://opencensus.io/service/exporters/honeycomb/tracing/
