### ISSUE TITLE
How does sampling work?

### ISSUE THREAD

**Issue by apechimp** [honeycombio/opencensus-exporter#6]
It's not clear how this exporter interacts with sampling. If I were to use the [Probability Sampler](https://godoc.org/go.opencensus.io/trace#ProbabilitySampler), it is not clear how to provide that sampling rate to this exporter. Moreover, if I wanted to use a dynamic sampling method, it doesn't seem like I'd be able to send the sampling rate over on a span by span basis. Should I just entirely avoid the opencensus sampler and do the sampling via configuration of `libhoney`?

**Comment by akvanhar** [comment]
Hi @apechimp ! I just merged https://github.com/honeycombio/opencensus-exporter/pull/7 in which I add the sampleRate to the event.
If you were to use the Probability Sampler, please also pass the sample fraction you choose to use to the exporter. (You can see [an example of that](https://github.com/honeycombio/opencensus-exporter/blob/master/example/main.go#L29) in the example app in this repo).
Thanks for the suggestion!
