### ISSUE TITLE
Allow for attribute mapping to trace fields

### ISSUE THREAD

**Issue by michaelwilde** [honeycombio/opencensus-exporter#9]
In the current release, we see the following fields in Honeycomb from OpenCensus
```
TraceID     string       `json:"trace.trace_id"`
	Name        string       `json:"name"`
	ID          string       `json:"trace.span_id"`
	ParentID    string       `json:"trace.parent_id,omitempty"`
	DurationMs  int          `json:"duration_ms,omitempty"`
	Timestamp   time.Time    `json:"timestamp,omitempty"`
	Annotations []Annotation `json:"annotations,omitempty"`
```
While I'm not totally sure now "Name" is mapped from OpenCensus to Honeycomb, It would be valuable to be able to map a field in OpenCensus to a column in Honeycomb.  

It might be that the use of "Attributes" from OpenCensus is the way to go so a user could have serviceName, query, shoe-size, hair-color, etc?  https://opencensus.io/core-concepts/tracing/#attributes

**Comment by akvanhar** [comment]
OpenCensus Attributes are a span-level feature.
But, in order to surface up a higher level ServiceName, I've merged https://github.com/honeycombio/opencensus-exporter/pull/11
